[platformio]
default_envs = receptor

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -O2

[env:emisor]
build_src_filter =
	+<emisor.cpp>
upload_port = COM9
monitor_port = COM9

[env:receptor]
build_src_filter =
	+<receptor.cpp>
upload_port = COM10
monitor_port = COM10